FROM node:18.0.0-alpine3.15

# Create app directory
WORKDIR /usr/src/service2

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./service2.js .
COPY ./start_service2.sh .


EXPOSE 8080
CMD [ "sh", "start_service2.sh" ]