version: '3.7'

services:
  service_1:
    build: 
      context: .
      dockerfile: Dockerfile.service1
    ports:
      - 3000:3000
  service_2:
    build: 
      context: .
      dockerfile: Dockerfile.service2
    ports:
      - 3001:3001
  service_3:
    build: 
      context: .
      dockerfile: Dockerfile.service3
    ports:
      - 3002:3002
      - 9464:9464
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
      - 9999:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
  zipkin:
    image: openzipkin/zipkin:latest
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411